In [1]:
import pandas as pd

# CSV 파일 로드
df = pd.read_csv('final_patient_status.csv')

# DEAD 상태인 행만 필터링
dead_patients_df = df[df['Event'] == 'DEAD']

# 결과 출력
dead_patients_df

Empty DataFrame
Columns: [Sequence, Time, Event, PatientID, Deadline, EmergencyStatus, PatientType]
Index: []

In [3]:
df

,Sequence,Time,Event,PatientID,Deadline,EmergencyStatus,PatientType
0,944,1000.0,UNFINISHED,1,inf,False,Naive_Patient
1,783,1000.0,UNFINISHED,2,1255.0,True,Emergence_Patient
2,747,1000.0,UNFINISHED,3,inf,False,Naive_Patient
3,773,1000.0,UNFINISHED,4,1041.0,True,Emergence_Patient
4,930,1000.0,UNFINISHED,5,inf,False,Naive_Patient
...,...,...,...,...,...,...,...
95,999,1000.0,UNFINISHED,96,1192.0,True,Emergence_Patient
96,990,1000.0,UNFINISHED,97,1488.0,True,Emergence_Patient
97,985,1000.0,UNFINISHED,98,1102.0,True,Emergence_Patient
98,993,1000.0,UNFINISHED,99,1003.0,True,Emergence_Patient
99,999,1000.0,UNFINISHED,100,inf,False,Naive_Patient